version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=addismap.settings
      - POSTGRES_DB=addismap
      - POSTGRES_USER=addismap
      - POSTGRES_PASSWORD=addismap
      - POSTGRES_HOST=db
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=addismap
      - POSTGRES_USER=addismap
      - POSTGRES_PASSWORD=addismap
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  static_volume:
